---
- name: prepare  env 
  hosts: work
  become: yes

  tasks:
 
  - name: install docker gpg key
    shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg  --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes "




  - name: env installation
    apt:
      update_cache: yes
      pkg:
      - rsync
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: latest
     
 
    
  - name: set up stable docker repo
    ansible.builtin.shell: 
      echo 
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian/ 
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


  - name: install docker
    apt:
      update_cache: yes
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io




- name: prepare testing env and build project
  hosts: testing_servers
  become: yes

  tasks:

  - name: env installation
    apt:
      update_cache: yes
      pkg:
      - git 
      - default-jdk 
      - maven
      
      
  - name: clone project from git
    ansible.builtin.git:
      repo: https://github.com/Alex-dzen/boxfuse-sample-java-war-hello.git
      dest: /pjt/boxfuse
  
  - name: compile with maven
    ansible.builtin.shell:
      mvn clean package
    args:    
      chdir: /pjt/boxfuse
      
  - name: rename hello
    command: mv /pjt/boxfuse/target/hello-1.0.war /pjt/boxfuse/myapp.war
  

  - name: copy Dockerfile
    ansible.builtin.shell:
      wget -r  192.168.1.7/Dockerfile
    args:
      chdir: /pjt/boxfuse
   
    
  - name: delete old version
    ansible.builtin.shell:
      docker rmi 192.168.1.7:8082/repository/docker/boxfuse:latest -f
  
  
  - name: build container image
    ansible.builtin.shell:   
      docker build --tag 192.168.1.7:8082/repository/docker/boxfuse:latest .
    args:    
      chdir: /pjt/boxfuse
      
  - name: login to repo
    ansible.builtin.shell:
      docker login -u {{nex_log}} -p {{nex_pas}} 192.168.1.7:8082 
  
  
  - name: push image to repo
    ansible.builtin.shell:
      docker push 192.168.1.7:8082/repository/docker/boxfuse:latest
    
    
- name: pull and start boxfuse
  hosts: prod_servers
  become: yes

  tasks:
    
  - name: login to repo
    ansible.builtin.shell:
      docker login -u {{nex_log}} -p {{nex_pas}} 192.168.1.7:8082
      
  - name: stop old container
    ansible.builtin.shell:
      docker stop 192.168.1.7:8082/repository/docker/boxfuse:latest
      
  - name: delete old version
    ansible.builtin.shell:
      docker rmi 192.168.1.7:8082/repository/docker/boxfuse:latest -f
    
  - name: pull image from repo
    ansible.builtin.shell:
      docker pull 192.168.1.7:8082/repository/docker/boxfuse:latest
     
      
  - name: start boxfuse
    ansible.builtin.shell:
      docker run -d -p 8080:8080 192.168.1.7:8082/repository/docker/boxfuse  
